on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: code lana
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup java environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build + Sonar Scan
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ secrets.SONAR_ORG }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: gitleaks scanning
        uses: gitleaks/gitleaks-action@v2

      - name: sonar quality gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
